name: 'Auto Merge PR'
description: 'Auto merge PR conditionally'

inputs:
  token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Is Dependabot?
      id: is-dependabot
      if: github.event.pull_request.user.login == 'dependabot[bot]'
      run: true
      shell: bash

    - name: Is patch update?
      id: patch-update
      if: >
        steps.is-dependabot.outcome == 'success' && contains(
          github.event.head_commit.message, 'version-update:semver-patch'
        )
      run: true
      shell: bash

    - uses: pascalgn/automerge-action@v0.16.2
      env:
        GITHUB_TOKEN: "${{ inputs.GITHUB_TOKEN }}"
        MERGE_LABELS: ""
        MERGE_METHOD: "squash"
        MERGE_COMMIT_MESSAGE: "automatic"
        MERGE_FILTER_AUTHOR: "dependabot[bot]"
        MERGE_FORKS: "true"
        MERGE_RETRIES: "6"
        MERGE_RETRY_SLEEP: "10000"
        MERGE_REQUIRED_APPROVALS: "${{
          (
            steps.is-dependabot.outcome == 'success' ||
            steps.patch-update.outcome == 'success'
          ) &&
          0 || 1
        }}"
        UPDATE_LABELS: ""
        UPDATE_METHOD: "rebase"
