name: 'Semgrep'
description: 'Run returntocorp/semgrep'

inputs:
  rules:
    description: 'Run with specific rules'
    required: true
    default: 'auto'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'
        cache-dependency-path: '${{ github.action_path }}/requirements.txt'
    - run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash
    - run: semgrep ci
      env:
        SEMGREP_RULES: ${{ inputs.rules }}
      shell: bash