name: 'Semgrep'
description: 'Run returntocorp/semgrep'

inputs:
  fail-on-severity:
    description: 'Defines the threshold for the level of severity'
    required: true
    default: 'moderate'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'
        cache-dependency-path: '${{ github.action_path }}/requirements.txt'
    - run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
    - run: semgrep ci
      env:
        SEMGREP_RULES: ${{ inputs.semgrep-rules }}
      shell: bash