name: 'Setup Go'
description: 'Run actions/setup-go'

inputs:
  go-version:
    description: 'Setup with specific version'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        check-latest: true
        go-version: '${{ inputs.go-version }}'
        go-version-file: ${{ inputs.go-version == '' && 'go.mod' || '' }}
        cache-dependency-path: '**/go.sum'
